# Generated by Django 2.2 on 2019-04-23 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title to display on browser tab header')),
                ('facebook', models.URLField(blank=True, verbose_name='URL for Facebook Page')),
                ('github', models.URLField(blank=True, verbose_name='URL for GitHub Profile')),
                ('linkedin', models.URLField(blank=True, verbose_name='URL for LinkedIn profile')),
                ('twitter', models.URLField(blank=True, verbose_name='URL for Twitter Profile')),
                ('email', models.EmailField(max_length=254)),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
