# Generated by Django 2.2 on 2019-04-23 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BingoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Card Title')),
                ('slug', models.SlugField()),
                ('free_space', models.CharField(default='Free Space', max_length=40)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('private', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bingo_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bingo Card',
                'verbose_name_plural': 'Bingo Cards',
            },
        ),
        migrations.CreateModel(
            name='BingoCardSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squares', to='cards.BingoCard')),
            ],
            options={
                'verbose_name': 'Bingo Square',
                'verbose_name_plural': 'Bingo Squares',
            },
        ),
    ]
